install.packages("devtools", repos = "https://cloud.r-project.org")
cat("devtools installed...\n")
devtools::install_github("STIMALiU/ComputerLabs", subdir = "RPackage")
cat("stimaRpackages...\n")
stimaRpackages::install_stima_packages()
